### ISSUE TITLE
Crashes on syntax error

### ISSUE THREAD

**Issue by laggingreflex** [slightlyfaulty/stylus-native-loader#3]
Nice lib! I've switched to this from stylus-loader.

I'm using webpack-dev-server with hot-reloading, so that webpack recompiles and reloads my web-app whenever I make changes to a stylesheet. 

Whenever there's a syntax error in the stylesheet it causes the webpack-dev-server to completely crash and exit.

```
i ｢wdm｣: Failed to compile.
internal/process/promises.js:213
        triggerUncaughtException(err, true /* fromPromise */);
        ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.dirname (path.js:583:5)
    at WatcherManager.watchFile (C:\...\node_modules\watchpack\lib\watcherManager.js:27:23)
    at Watchpack.<anonymous> (C:\...\node_modules\watchpack\lib\watchpack.js:38:49)
    at Array.map (<anonymous>)
    at Watchpack.watch (C:\...\node_modules\watchpack\lib\watchpack.js:37:28)
    at NodeWatchFileSystem.watch (C:\...\node_modules\webpack\lib\node\NodeWatchFileSystem.js:70:16)
    at Watching.watch (C:\...\node_modules\webpack\lib\Watching.js:114:48)
    at C:\...\node_modules\webpack\lib\Watching.js:101:10
    at eval (eval at create (C:\...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:1)
    at Immediate.<anonymous> (C:\...\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:84:13)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\...\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:3:103)
    at _next (C:\...\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:5:194)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
undefined
internal/process/promises.js:213
        triggerUncaughtException(err, true /* fromPromise */);
        ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
  code: 'ERR_UNHANDLED_REJECTION'
```

Stylus-loader was able to handle syntax errors and just show "Failed to compile" (rather than crash/exiting).

**Comment by slightlyfaulty** [comment]
Thanks very much for the bug report. Could you tell me what version of Webpack you're seeing this with?

**Comment by slightlyfaulty** [comment]
Strange, I can't seem to reproduce this. I'm using `webpack-dev-server` with HMR and it handles Stylus compile errors without a problem.

**Comment by laggingreflex** [comment]
Hmm, I tested again, and it seems to be a Windows issue. (I'm on Windows 10.) Running on [WSL] it doesn't crash. 

One thing to note is that the error that I get when using this (stylus-native-loader) over stylus-loader is different, particular the last part. 

 



[wsl]: https://docs.microsoft.com/en-us/windows/wsl/

```
i ｢wdm｣: Compiling...
× ｢wdm｣: Hash: 9b95e1ef320c58e12067
...<truncated lines>
ERROR in ./src/frontend/styles/base.styl (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/stylus-native-loader/dist/cjs.js!./src/frontend/styles/base.styl)
Module build failed (from C:/.../node_modules/stylus-native-loader/dist/cjs.js):
ParseError: C:\...\src\frontend\styles\base.styl:19:1
   18| #app
   19|
-------^
expected "indent", got "eos"
...<truncated lines>
i ｢wdm｣: Failed to compile.
```

While both libraries output the same error up until here ("Failed to compile"), there are additional error lines below that only appear when using stylus-native-loader:

```
internal/process/promises.js:213
        triggerUncaughtException(err, true /* fromPromise */);
        ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.dirname (path.js:583:5)
    at WatcherManager.watchFile (C:\...\node_modules\watchpack\lib\watcherManager.js:27:23)
    at Watchpack.<anonymous> (C:\...\node_modules\watchpack\lib\watchpack.js:38:49)
    at Array.map (<anonymous>)
    at Watchpack.watch (C:\...\node_modules\watchpack\lib\watchpack.js:37:28)
    at NodeWatchFileSystem.watch (C:\...\node_modules\webpack\lib\node\NodeWatchFileSystem.js:70:16)
    at Watching.watch (C:\...\node_modules\webpack\lib\Watching.js:114:48)
    at C:\...\node_modules\webpack\lib\Watching.js:101:10
    at eval (eval at create (C:\...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:1)
    at Immediate.<anonymous> (C:\...\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:84:13)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\...\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:3:103)
    at _next (C:\...\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:5:194) {
  code: 'ERR_INVALID_ARG_TYPE'
}
undefined
internal/process/promises.js:213
        triggerUncaughtException(err, true /* fromPromise */);
        ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

These additional error lines appear in both native Windows command prompt as well as WSL Ubuntu shell. On Windows command prompt though, it results in complete exit of the process, whereas on WSL it stays in process and continues to function. 

Do these extra error lines appear for you? Could these be a symptom of a problem somewhere?

**Comment by slightlyfaulty** [comment]
Thanks for the additional info. I've managed to reproduce and fix the issue.

Please can you give the latest update a try and let me know if it's working on your side.

**Comment by laggingreflex** [comment]
Yep, tried 1.4.0, it no longer crashes. Super!

**Comment by slightlyfaulty** [comment]
Awesome! Thanks for catching this. Happy Stylusing 😎
